const Purchase = require('../model/Purchase');
const PurchaseItem = require('../model/PurchaseItem');
const Supplier = require('../model/Supplier');
const User = require('../model/User');
const Product = require('../model/Product');

const createPurchase = async (req, res) => {
  try {
    const { supplier_id, manager_id, store_id, subtotal, discount } = req.body;

    // Check supplier
    const supplier = await Supplier.findById(supplier_id);
    if (!supplier) {
      return res.status(404).json({ success: false, message: 'Supplier not found' });
    }

    // Check manager
    const manager = await User.findById(manager_id);
    if (!manager) {
      return res.status(404).json({ success: false, message: 'Manager not found' });
    }

    const purchase = new Purchase({
      supplier_id,
      manager_id,
      store_id,
      subtotal,
      discount
      // purchase_order_number auto-generated by pre('save')
    });

    await purchase.save();

    res.status(201).json({
      success: true,
      message: 'Purchase created successfully',
      data: purchase
    });

  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
};


const getAllPurchases = async (req, res) => {
  try {
    const purchases = await Purchase.find()
      .populate('supplier_id', 'name')
      .populate('manager_id', 'name')
      .populate('store_id', 'store_name') // change field name accordingly
      .sort('-createdAt');

    res.status(200).json({
      success: true,
      count: purchases.length,
      data: purchases
    });

  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
};


const getPurchaseById = async (req, res) => {
  try {
    const purchase = await Purchase.findById(req.params.id)
      .populate('supplier_id', 'name')
      .populate('manager_id', 'name')
      .populate('store_id', 'store_name');

    if (!purchase) {
      return res.status(404).json({ success: false, message: 'Purchase not found' });
    }

    // Optional: populate items
    const items = await PurchaseItem.find({ purchase_id: purchase._id })
      .populate('product_id', 'product_name sell_price');

    res.status(200).json({
      success: true,
      data: { purchase, items }
    });

  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
};


const deletePurchase = async (req, res) => {
  try {
    const purchase = await Purchase.findById(req.params.id);
    if (!purchase) {
      return res.status(404).json({ success: false, message: 'Purchase not found' });
    }

    // Delete all related purchase items
    await PurchaseItem.deleteMany({ purchase_id: purchase._id });

    await Purchase.findByIdAndDelete(req.params.id);

    res.status(200).json({
      success: true,
      message: 'Purchase and its items deleted successfully'
    });

  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
};

module.exports = {deletePurchase,getPurchaseById,getAllPurchases, createPurchase};